### ISSUE TITLE
potential bug in `__inc__`

### ISSUE THREAD

**Issue by ekarais** [flooreijkelboom/equivariant-simplicial-mp#1]
In `simplicial_data/simplicial_data.py`, specifically within the `__inc__` method of `SimplicialComplexData`, I see that the `x_i` attributes of SimplicialComplexData (which hold node indices) are not incremented:

```python
def __inc__(self, key: str, value: Any, *args, **kwargs) -> Any:
        if 'adj' in key:
            i, j = key[4], key[6]
            return torch.tensor([[getattr(self, f'x_{i}').size(0)], [getattr(self, f'x_{j}').size(0)]])
        elif key == 'inv_0_0':
            return torch.tensor([[getattr(self, f'x_0').size(0)], [getattr(self, f'x_0').size(0)]])
        elif key == 'inv_0_1':
            return torch.tensor([[getattr(self, f'x_0').size(0)], [getattr(self, f'x_0').size(0)]])
        elif key == 'inv_1_1':
            return torch.tensor([[getattr(self, f'x_0').size(0)], [getattr(self, f'x_0').size(0)], [getattr(self, f'x_0').size(0)]])
        elif key == 'inv_1_2':
            return torch.tensor([[getattr(self, f'x_0').size(0)], [getattr(self, f'x_0').size(0)], [getattr(self, f'x_0').size(0)]])
        else:
            return super().__inc__(key, value, *args, **kwargs)
```
Regarding what happens in the call to the parent, I found this paragraph on [`pytorch-geometric`'s documentation](https://pytorch-geometric.readthedocs.io/en/latest/advanced/batching.html):

> In its most general form, the PyG [DataLoader](https://pytorch-geometric.readthedocs.io/en/latest/modules/loader.html#torch_geometric.loader.DataLoader) will automatically increment the edge_index tensor by the cumulated number of nodes of all graphs that got collated before the currently processed graph, and will concatenate edge_index tensors (that are of shape [2, num_edges]) in the second dimension. The same is true for face tensors, i.e., face indices in meshes. All other tensors will just get concatenated in the first dimension without any further increasement of their values.

So it seems that the `x_i` attributes (which hold node indices) are not incremented.

In the beginning of the forward pass of the EMPSN model, the node indices in `x_i` are used to index into `graph.x`, from which the node features are retrieved. Given that the indices in `x_i` are not incremented during batching, how does EMPSN correctly index into `graph.x`? To me, it looks like the node features used during the forward pass do not correspond to the nodes of the graphs in the batch, but instead they mostly correspond to the nodes of the first few graphs in the batch. If this is the case, do you have an intuition for how EMPSN can outperform many other models despite not having access to the atom features? If this is not the case and I am misunderstanding the code, can you please explain what I'm missing?

**Comment by flooreijkelboom** [comment]
Thanks a lot! I am not sure how this bug slipped in; I probably messed up cleaning the code. You are right and I fixed the issue, this bug did not exist when doing the experiments in my private repo.

Best, Floor

**Comment by flooreijkelboom** [comment]
Hey, thanks a lot again for noticing the bug. Apparently, I introduced a new one during the fix. I just uploaded a new version and it seems to work now!
